spring:
  datasource:
    url: jdbc:h2:file:./h2db/metadata-tools;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: nz7wjNzReAePJS4VEuPd